### ISSUE TITLE
What version of Eclipse Kepler ?

### ISSUE THREAD

**Issue by jjcasalo** [IBM-i2/Intelligence-Analysis-Platform#1]
In the guide, it says to install Eclipse Kepler.  But which version/package ?
When I look at the Eclipse page, it offers me 13 different options/packages.

Which one should we use ?

The available packages are (as of June 2014) 
 - Eclipse Standard 4.3.2, 200 MB
 - Eclipse IDE for Java EE Developers, (250 MB)
 - Eclipse IDE for Java Developers, 153 MB
 - JRebel for Eclipse IDE
 - Eclipse IDE for C/C++ Developers, 143 MB
 - Eclipse Modeling Tools, 293 MB
 - Eclipse IDE for Java and DSL Developers, 270 MB
 - Eclipse for RCP and RAP Developers, 237 MB
 - Eclipse for Testers, 99 MB
 - Eclipse IDE for Java and Report Developers, 287 MB
 - Eclipse for Parallel Application Developers, 216 MB
 - Eclipse IDE for Automotive Software Developers (includes Incubating components), 196 MB
 - Eclipse for Scout Developers, 289 MB

**Comment by stu-w** [comment]
As the page is now updated wit the package information, I'm going to mark this as fixed. Thanks for the heads-up.
