### ISSUE TITLE
Missing mandatory properties in Developer Essentials for IAP 3.0.11

### ISSUE THREAD

**Issue by scomcgill** [IBM-i2/Intelligence-Analysis-Platform#15]
When following the developer_essentials_example_daod.md instructions, the "build -t deploy" step fails with the following:

======================= WARNINGS (1) =======================
 + configuration/fragments/da-subset-filesystem-example/WEB-INF/classes/ApolloServerSettingsDaodMandatory.properties:
   - The "MainSearchIndex" property has not been set.

============================================================
======================== ERRORS (1) ========================
 + configuration/fragments/da-subset-filesystem-example/WEB-INF/classes/ApolloServerSettingsDaodMandatory.properties:
   - The "IExternalDataItemRetriever" property has not been set. This is required when EDRS is enabled.

============================================================

Validation failed. Correct errors, and review any warnings.
:da-subset-rest-example:deploy FAILED

I checked the configuration/fragments/da-subset-filesystem-example/WEB-INF/classes/ApolloServerSettingsDaodMandatory.properties and the MainSearchIndex and IExternalDataItemRetriever properties are not there, not even commented out.

Could you please provide the missing properties.

**Comment by boalesth** [comment]
Hi Scomcgill,
Sorry for the delay.

The warning message can be safely ignored. It will not cause issues with the deployment.

Regarding the Error message that you have received, if you are indeed setting up one of the examples, you will find that you have not correctly set the data source flags in topology.xml after running addDaodDataSource:
<iap-data-source id="daod1" ar="false">
   <DataSource EdrsGetContextSupported="false" ScsBrowseSupported="true"
               ScsSearchSupported="true" ScsPresent="true"
               ScsFilteredSearchSupported="false" EdrsPresent="false"
               ScsNetworkSearchSupported="false" Id="" SesPresent="true"
               Version="0" EdrsGetLatestItemsSupported="false"
               ScsDumbbellSearchSupported="false">
      <Shape>DAOD</Shape>
      <Name>da-subset-filesystem-example</Name>
   </DataSource>
</iap-data-source>

If you update your topology file to match the instructions, and then redeploy the example the error should be resolved.

Thanks

Esther
