### ISSUE TITLE
problems about convert data source into a form that is compatible with the iap

### ISSUE THREAD

**Issue by tantairs** [IBM-i2/Intelligence-Analysis-Platform#16]
Hi,
The version of my iap is 3.0.11.0, when i do the convertion from  data source to a form that is compatible with the iap  following the document(data_acquisition_developer_guide). which as following picture.( i have defined a schema by myself)
![default](https://cloud.githubusercontent.com/assets/3755786/9623696/02119322-5177-11e5-86c0-01d3abf6ca17.PNG)
.I can't run the command: python da-setup.py -t generate-mapping-jar -x IapSchema -z xsdFiles -o JarFiles. I check my file that are ended with gradle. I can't find the solusion following this document (data_acquisition_developer_guide). So how can i do the conversion with this version ? 
                                                                                                                                              thinks for reply.

**Comment by boalesth** [comment]
Hi Tantairs,

The guide hasn't been updated yet, but for 3.0.11 you will need to run the gradle equivalent:
```
setup -t generateMappingJar -x IapSchema -z XsdFiles -o JarFiles
```
For example:
```
setup -t generateMappingJar -x "C:\dev\is-ingestion.xml" -o "c:\temp\is.jar" -z "c:\temp"
```

For a full list of the commands that are supported at 3.0.11, refer to the embedded help:
```
setup -h
```
For help with da specific commands use:
```
setup -dh
```
Thanks

Esther

**Comment by tantairs** [comment]
Thanks for your reply,i will have a try.
