### ISSUE TITLE
List of Errors

### ISSUE THREAD

**Issue by brunocnoliveira** [IBM-i2/Intelligence-Analysis-Platform#7]
Hello,

Where can I find the list of errors returned by IAP? I need to know all errors that IAP sdk might throws in order to map a set of error codes in my application.

Anyone can help me?

Thanks a lot.

**Comment by stu-w** [comment]
Hi, Bruno. Where errors may be returned by API calls the relevant exceptions are listed in the documentation. 

(I'm marking this as closed as the behavior is as intended.)
